#! /bin/sh

#set -x

. $SNAP/config

PLIST="$(snapctl get playlist)"
PORT="$(snapctl get port)"

set_name() {
  CUR="$(grep -B1 "$1" $PLIST |head -1|sed 's/.*logo=\"//;s/\"//')"
  #IMG="<img src=${CUR%,*}>"
  NME="${CUR#*,}"
  #sed -i "s;^.*class=logo.*$;<div class=logo>${IMG}</div>;" $HTMDIR/index.html
  #sed -i "s;^.*class=name.*$;<div class=name>${NME}</div>;" $HTMDIR/index.html
  echo "PLAYING: $NME" >"$OUTFIFO"
}

switch_chan() {
  NXT="$1"

  [ -n "$NXT" ] || $NXT="$(cat $CHANNEL)"
  echo "$NXT" >$CHANNEL

  if ! kill -9 "$(cat $SNAP_DATA/omx.pid)"; then
    snapctl restart ${SNAP_NAME}.omx-player
  fi
  set_name "$NXT"
}

while true; do
     HTM="$(cat $HTMDIR/index.html)"
     RET="$(/bin/echo -e "HTTP/1.1 200 OK\r\n\n${HTM}" | \
        nc -l "$PORT" | grep -v favico | grep GET | \
        sed 's/^GET \///;s/ .*$//'|head -1)"
     case $RET in
       up)
         while true; do
           NXT="$(grep "$(cat $CHANNEL)" -A2 "$PLIST" |tail -1)"
           switch_chan "$NXT"

           if ! grep -q "have a nice day" "$OUTFIFO"; then
             break
           fi
         done
         ;;
       down)
         while true; do
           NXT="$(grep "$(cat $CHANNEL)" -B2 "$PLIST" | grep -v "^#" | head -1 )"
           switch_chan "$NXT"

           if ! grep -q "have a nice day" "$OUTFIFO"; then
             break
           fi
         done
         ;;
       vup)
         echo -n '+' >"$INFIFO"
         ;;
       vdown)
         echo -n '-' >"$INFIFO"
         ;;
     esac
done
