name: rpi-iptv-player
version: '0.1'
summary: OpenMax IPTV player for the raspberry pi
description: |
  OMXPlayer is a commandline OMX player for the Raspberry PI.
  It was developed as a testbed for the XBMC Raspberry PI implementation
  and is quite handy to use standalone.

  OMXPlayer can not be used with the KMS driver on Ubuntu Core, make sure
  to comment "dtoverlay=vc4-kms-v3d" in /boot/uboot/config.txt (note that
  this in turn disables support for mir-kiosk). It is also recommended to
  set "gpu_mem=128" (or higher) when playing 1080p60 video.

grade: stable
confinement: strict

architectures:
  - build-on: armhf
    run-on: armhf

apps:
  set-permissions:
    command: set-permissions
    daemon: oneshot
    plugs:
      - opengl
  omx-player:
    command: omx-player
    daemon: simple
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/omxplayer:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/samba:$LD_LIBRARY_PATH
      INFIFO: "$SNAP_DATA/omxfifo"
      OUTFIFO: "$SNAP_DATA/outfifo"
      CHANNEL: "$SNAP_DATA/channel"
    plugs:
      - framebuffer
      - network
      - network-bind
      - opengl
  ipplayer-pi:
    command: ipplayer
    daemon: simple
    plugs:
      - network
      - network-bind

hooks:
  configure:
    plugs:
      - network
      - network-bind
  install:
    plugs:
      - network
      - network-bind

parts:
  vc4-libs:
    source: https://github.com/raspberrypi/userland.git
    source-depth: 1
    plugin: nil
    override-build: |
      git apply ../../../vc-libs-neon.patch
      ./buildme .
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr
      cp -av ./build/raspberry/release/opt/vc/lib $SNAPCRAFT_PART_INSTALL/usr/
      cp -av ./build/raspberry/release/opt/vc/include $SNAPCRAFT_PART_INSTALL/usr/
    build-packages:
      - cmake
      - g++
  player:
    plugin: make
    source: https://github.com/popcornmix/omxplayer.git
    source-depth: 1
    override-build: |
      git apply ../../../omxplayer-neon-and-build.patch
      make ffmpeg
      snapcraftctl build
      cp -av ../../../set-permissions $SNAPCRAFT_PART_INSTALL/usr/bin
    after: [ vc4-libs ]
    build-packages:
      - curl
      - libasound2-dev
      - libva1
      - libpcre3-dev
      - libidn11-dev
      - libboost-dev
      - libfreetype6-dev
      - libdbus-1-dev
      - libssl-dev
      - libssh-dev
      - libsmbclient-dev
      - subversion
    stage-packages:
      - fonts-dejavu-core
      - fonts-dejavu-extra
      - libasound2
      - libbluray1
      - libfontconfig1
      - libgme0
      - libgomp1
      - libgsm1
      - libicu55
      - libmodplug1
      - libmp3lame0
      - libogg0
      - libopenjpeg5
      - libopus0
      - liborc-0.4-0
      - librtmp1
      - libschroedinger-1.0-0
      - libshine3
      - libsnappy1v5
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libtheora0
      - libtwolame0
      - libva1
      - libvorbis0a
      - libvorbisenc2
      - libvpx3
      - libwavpack1
      - libwebp5
      - libx264-148
      - libx265-79
      - libxml2
      - libxvidcore4
      - libzvbi0
      - libasn1-8-heimdal
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libldb1
      - libroken18-heimdal
      - libsasl2-2
      - libsmbclient
      - libssh-4
      - libtalloc2
      - libtdb1
      - libtevent0
      - libwbclient0
      - libwind0-heimdal
      - samba-libs
      - libdb5.3
  ipplayer:
    after: [ player ]
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av ipplayer/ipplayer $SNAPCRAFT_PART_INSTALL/bin/
      cp -av ipplayer/omx-player $SNAPCRAFT_PART_INSTALL/bin/
      cp -av ipplayer/index.html $SNAPCRAFT_PART_INSTALL/
      cp -av ipplayer/channels.m3u $SNAPCRAFT_PART_INSTALL/
      cp -av ipplayer/config $SNAPCRAFT_PART_INSTALL/
